[project]
name = 'bitdap'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = [
    {contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard", remap = "sip-010-trait"},
    {contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait", remap = "nft-trait"}
]
[contracts.bitdap]
path = 'contracts/bitdap.clar'
clarity_version = 4
epoch = 'latest'

[contracts.bitdap-token]
path = 'contracts/bitdap-token.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
